# Config updated for version ${project.version}
# **** NOTE ****
# THIS IS A DEMO CONFIG AND WONT BE USED

player:
  kill_coin_gain: 10

games:
  start_percentage: 70
  start_timer: 10

lobby-scoreboard:
  enabled: true
  displayName: "Lobby Scoreboard"
  lines:
    - "Lobby Scoreboard"

game-scoreboard:
  enabled: true
  displayName: "Game Scoreboard"
  lines:
    - "Game Scoreboard"